CREATE SCHEMA IF NOT EXISTS `${DS_RAW_BILLING}`;
CREATE TABLE IF NOT EXISTS `${DS_RAW_BILLING}`.idx_stg_lac_mh_os_archive (
  filename STRING,
  filedate STRING,
  oth_num STRING,
  mrn STRING,
  grp STRING,
  pat_nm STRING,
  inv_num STRING,
  orig_inv_num STRING,
  thru_ser_dt DATE,
  txn_ser_dt DATE,
  inv_ser_dt DATE,
  proc_description STRING,
  proc__1 STRING,
  units STRING,
  dx_one__3 STRING,
  dx_one__1 STRING,
  dx_two__3 STRING,
  dx_three__3 STRING,
  dx_four__3 STRING,
  mod STRING,
  prov STRING,
  u_supervising_prov STRING,
  referring_phy_dict STRING,
  billing_area STRING,
  div_1 STRING,
  loc STRING,
  txn_chg_amt STRING,
  tot_chg STRING,
  inv_bal STRING,
  orig_fsc STRING,
  fsc STRING,
  clm_run_num STRING,
  clm_run_dt STRING,
  inv_cre_dt STRING,
  post_pd STRING,
  post_dt STRING,
  ssn STRING,
  dob STRING,
  sex STRING,
  u_acsn_num STRING,
  prior_auth_num STRING,
  hos__1 STRING,
  fsc_1__1 STRING,
  im_ins_registration_1_1 STRING,
  fsc_2__1 STRING,
  im_ins_registration_2_1 STRING,
  fsc_3__1 STRING,
  im_ins_registration_3_1 STRING,
  fsc_4__1 STRING,
  im_ins_registration_4_1 STRING,
  mis STRING
)
OPTIONS (
  description='Migrated from shc_incomingphysician.idx_stg_lac_mh_os_archive'
);
