CREATE SCHEMA IF NOT EXISTS `${DS_RAW_BILLING}`;
CREATE TABLE IF NOT EXISTS `${DS_RAW_BILLING}`.idx_stg_osar (
  filename STRING,
  filedate STRING,
  oth_num STRING,
  mrn STRING,
  grp STRING,
  pat_nm STRING,
  inv_num STRING,
  orig_inv_num STRING,
  thru_ser_dt STRING,
  txn_ser_dt STRING,
  inv_ser_dt STRING,
  proc_1 STRING,
  proc_2 STRING,
  units STRING,
  dx_one_3 STRING,
  dx_one_1 STRING,
  dx_two_3 STRING,
  dx_three_3 STRING,
  dx_four_3 STRING,
  mod STRING,
  prov STRING,
  u_supervising_prov STRING,
  referring_phy_dict STRING,
  billing_area STRING,
  division STRING,
  loc STRING,
  txn_chg_amt STRING,
  tot_chg STRING,
  inv_bal STRING,
  orig_fsc STRING,
  fsc STRING,
  clm_run_num STRING,
  clm_run_dt STRING,
  inv_cre_dt STRING,
  post_pd STRING,
  post_dt STRING,
  ssn STRING,
  dob STRING,
  sex STRING,
  u_acsn_num STRING,
  prior_auth_num STRING,
  hos_1 STRING,
  fsc_1_1 STRING,
  ins_registration_1_1 STRING,
  fsc_2_1 STRING,
  ins_registration_2_1 STRING,
  fsc_3_1 STRING,
  ins_registration_3_1 STRING,
  fsc_4_1 STRING,
  ins_registration_4_1 STRING
)
OPTIONS (
  description='Migrated from shc_incomingphysician.idx_stg_osar'
);
