CREATE SCHEMA IF NOT EXISTS `${DS_RAW_BILLING}`;
CREATE TABLE IF NOT EXISTS `${DS_RAW_BILLING}`.idx_stg_linepay_archive (
  filename STRING,
  filedate STRING,
  oth_num STRING,
  inv_num STRING,
  txn_num STRING,
  inv_bal STRING,
  post_dt_1 STRING,
  post_pd_1 STRING,
  post_dt_2 STRING,
  post_pd_2 STRING,
  batch_num STRING,
  pay_code_2 STRING,
  pay_amt STRING,
  debit_amt STRING,
  credit_amt STRING,
  adj_amt STRING,
  profile_amt STRING,
  app_amt STRING,
  allowed_amt STRING,
  copay STRING,
  coins_amt STRING,
  ded_amt STRING,
  batch_bank_dep_dt STRING,
  fsc_at_payment_2 STRING,
  bar_b_inv_fsc_2 STRING,
  proc_2 STRING,
  ser_dt STRING,
  mod_1 STRING,
  mod_2 STRING,
  mod_3 STRING,
  chg_amt STRING,
  rvu_work_comp STRING,
  units STRING,
  bar_b_inv_grp_2 STRING,
  additional1 STRING,
  additional2 STRING,
  additional3 STRING,
  additional4 STRING,
  additional5 STRING
)
OPTIONS (
  description='Migrated from shc_incomingphysician.idx_stg_linepay_archive'
);
