CREATE SCHEMA IF NOT EXISTS `${DS_RAW_BILLING}`;
CREATE TABLE IF NOT EXISTS `${DS_RAW_BILLING}`.idx_stg_invoice (
  filename STRING,
  filedate STRING,
  inv_num STRING,
  oth_num STRING,
  orig_inv_num STRING,
  orig_inv_from_split STRING,
  tot_chg STRING,
  inv_bal STRING,
  bar_b_acct_stmt_cur_bal STRING,
  fsc_2 STRING,
  prov_2 STRING,
  loc_3 STRING,
  billing_area_3 STRING,
  hos_3 STRING,
  grp_2 STRING,
  div_3 STRING,
  ref_phy_dict_2 STRING,
  clm_run_num STRING,
  fsc_26_3 STRING,
  orig_fsc_2 STRING,
  ins_registration_1_1 STRING,
  ser_dt STRING,
  inv_cre_dt STRING,
  clm_run_dt STRING,
  first_clm_rundt STRING,
  stmt_dt STRING,
  inv_cre_pd STRING,
  dx_one_3 STRING,
  dx_two_3 STRING,
  dx_three_3 STRING,
  dx_four_3 STRING,
  mrn STRING,
  ins_invoice_24_7 STRING,
  additional1 STRING,
  additional2 STRING,
  additional3 STRING,
  additional4 STRING,
  additional5 STRING
)
OPTIONS (
  description='Migrated from shc_incomingphysician.idx_stg_invoice'
);
