CREATE SCHEMA IF NOT EXISTS `${DS_RAW_BILLING}`;
CREATE TABLE IF NOT EXISTS `${DS_RAW_BILLING}`.idx_stg_lac_txn (
  filename STRING,
  filedate STRING,
  inv_num STRING,
  corr_inv_num STRING,
  orig_inv_num STRING,
  txn_num STRING,
  billing_area_3 STRING,
  grp_2 STRING,
  loc_3 STRING,
  prev_fsc_2 STRING,
  fsc_1 STRING,
  im_ins_registration1_1 STRING,
  im_ins_registration1_2 STRING,
  im_ins_registration1_3 STRING,
  im_ins_registration1_4_1 STRING,
  fsc_26_3 STRING,
  chg_amt STRING,
  pay_amt STRING,
  adj_amt STRING,
  cr_amt STRING,
  inv_bal STRING,
  debit_amt STRING,
  proc_2 STRING,
  mod_1 STRING,
  mod_2 STRING,
  mod_3 STRING,
  dx_num STRING,
  pay_code_2 STRING,
  units STRING,
  post_dt STRING,
  tes_txn_creat_dt STRING,
  clm_run_dt STRING,
  bank_dep_dt STRING,
  ser_dt STRING,
  rvu STRING,
  rvu_work_comp STRING,
  fsc_2 STRING,
  ims_ins_invoice_24_7 STRING,
  post_pd STRING,
  additional1 STRING,
  additional2 STRING,
  additional3 STRING
)
OPTIONS (
  description='Migrated from shc_incomingphysician.idx_stg_lac_txn'
);
