CREATE SCHEMA IF NOT EXISTS `${DS_RAW_BILLING}`;
CREATE TABLE IF NOT EXISTS `${DS_RAW_BILLING}`.transactionedits_lacphy_mh_archive (
  filename STRING,
  filedate STRING,
  organizationgroupid STRING,
  tes_batch STRING,
  enc STRING,
  pt_last_nm STRING,
  pt_first_nm STRING,
  dob STRING,
  ssn STRING,
  dos STRING,
  fsc STRING,
  fsc_n STRING,
  prov STRING,
  adm_dt STRING,
  dsch_dt STRING,
  inj_dt STRING,
  cre_dt STRING,
  bill_area STRING,
  div STRING,
  loc STRING,
  hos STRING,
  prior_auth STRING,
  ref_phy STRING,
  ini STRING,
  cpt STRING,
  mod STRING,
  dx1 STRING,
  dx2 STRING,
  dx3 STRING,
  dx4 STRING,
  dx5 STRING,
  dx6 STRING,
  dx7 STRING,
  dx8 STRING,
  dx9 STRING,
  dx10 STRING,
  units STRING,
  chg_amt STRING,
  status STRING,
  edit STRING,
  clmrn STRING,
  acsn_num STRING,
  comments_1 STRING,
  comments_2 STRING,
  description STRING,
  carrier_code STRING,
  npi STRING
)
OPTIONS (
  description='Migrated from shc_incomingphysician.transactionedits_lacphy_mh_archive'
);
