CREATE SCHEMA IF NOT EXISTS `${DS_GOLD_ANALYTICS}`;
CREATE TABLE IF NOT EXISTS `${DS_GOLD_ANALYTICS}`.aradjustments (
  adjustmentid INT64,
  accountheaderid INT64,
  payercode STRING,
  financialclasscode STRING,
  facilityid INT64,
  serviceproviderid INT64,
  filefrequency STRING,
  filetype STRING,
  recordreceiveddate DATETIME,
  accountnumber STRING,
  mrn STRING,
  lineitemnumber STRING,
  diagnosiscode STRING,
  diagnosiscodetype STRING,
  revenuecode STRING,
  procedurecode STRING,
  placeofservice STRING,
  billtypecode STRING,
  procedurecodemodifier STRING,
  reasoncode STRING,
  reasondescription STRING,
  placementdate DATETIME,
  servicefromdate DATETIME,
  servicetodate DATETIME,
  claimadjustmentdate DATETIME,
  claimreceiveddate DATETIME,
  adjustedamount NUMERIC,
  insuranceadjustedamount STRING,
  lineiteminsuranceadjustedamount STRING,
  selfpayadjustedamount STRING,
  lineitemselfpayadjustedamount STRING,
  transactioncode STRING,
  transactiondescription STRING,
  accountbalance NUMERIC,
  adjustmenttype STRING,
  claimreferencenumber STRING,
  createdby STRING,
  createddate DATETIME,
  modifiedby STRING,
  modifieddate DATETIME,
  recordstartdate DATETIME,
  recordenddate DATETIME,
  sourceprogramid INT64,
  activeflag STRING,
  writeoff NUMERIC,
  adjustmentpostingperiod DATETIME,
  credits NUMERIC,
  units STRING,
  sequencenumber INT64,
  approvedamount NUMERIC,
  coinsuranceamount NUMERIC,
  payamount NUMERIC,
  deductibleamount NUMERIC,
  profileamount NUMERIC,
  procedurecodemodifier2 STRING,
  procedurecodemodifier3 STRING,
  tag STRING,
  accounttag STRING,
  patientliability NUMERIC,
  allowedamount NUMERIC,
  npi STRING,
  payorid STRING,
  organizationgroupid STRING,
  batch_id STRING
)
PARTITION BY DATE(recordreceiveddate)
CLUSTER BY organizationgroupid
OPTIONS (
  description='Migrated from shc_gold.aradjustments'
);
