CREATE SCHEMA IF NOT EXISTS `${DS_GOLD_ANALYTICS}`;
CREATE TABLE IF NOT EXISTS `${DS_GOLD_ANALYTICS}`.dmcharges (
  accountnumber STRING,
  chargeid INT64,
  mrn STRING,
  payercode STRING,
  financialclasscode STRING,
  facilityname STRING,
  billingarea STRING,
  department STRING,
  division STRING,
  attendingprovidername STRING,
  renderingprovidername STRING,
  placementdate DATETIME,
  invoicecreationperiod DATETIME,
  servicefromdate DATETIME,
  servicethroughdate DATETIME,
  diagnosiscode1 STRING,
  diagnosiscode1type STRING,
  diagnosiscode1description STRING,
  diagnosiscode2 STRING,
  diagnosiscode2type STRING,
  diagnosiscode2description STRING,
  principaldiagnosiscode STRING,
  principaldiagnosiscodedescription STRING,
  originalprocedurecode STRING,
  originalprocedurecodedescription STRING,
  procedurecode STRING,
  procedurecodedescription STRING,
  procedurecodemodifier1 STRING,
  placeofservice STRING,
  placeofservicename STRING,
  revenuecode STRING,
  servicetypecode STRING,
  quantity NUMERIC,
  lineitemchargeamount NUMERIC,
  lineitemremainingbalance NUMERIC,
  createdby STRING,
  createddate DATETIME,
  modifiedby STRING,
  modifieddate DATETIME,
  placementfinancialclass STRING,
  placementpayor STRING,
  placementfacility STRING,
  providername STRING,
  transactionnumber INT64,
  procedurecodemodifier2 STRING,
  procedurecodemodifier3 STRING,
  servicingprovidername STRING,
  referringprovidername STRING,
  primarypayer STRING,
  secondarypayer STRING,
  tertiarypayer STRING,
  payerchargeamount NUMERIC,
  selfchargeamount NUMERIC,
  organizationgroupid STRING,
  batch_id STRING
)
PARTITION BY DATE(servicefromdate)
CLUSTER BY financialclasscode, placementpayor, department
OPTIONS (
  description='Migrated from shc_datamart.dmcharges'
);
