CREATE SCHEMA IF NOT EXISTS `${DS_GOLD_ANALYTICS}`;
CREATE TABLE IF NOT EXISTS `${DS_GOLD_ANALYTICS}`.dmkpimonthend (
  organizationname STRING,
  processeddate DATETIME,
  invoicecreationperiod DATETIME,
  accountvolume INT64,
  originalbalance NUMERIC,
  totalcharges NUMERIC,
  unmatchedinsurancepaymentamount NUMERIC,
  unmatchedselfpaymentamount NUMERIC,
  unmatcheddebitamount NUMERIC,
  unmatchedrefundamount NUMERIC,
  unmatchedtotaladjustment NUMERIC,
  unmatchedwriteoffamount NUMERIC,
  unmatchedcredits NUMERIC,
  matchedinsurancepaymentamount NUMERIC,
  matchedselfpaymentamount NUMERIC,
  matcheddebitamount NUMERIC,
  matchedrefundamount NUMERIC,
  matchedtotaladjustment NUMERIC,
  matchedwriteoffamount NUMERIC,
  matchedcredits NUMERIC,
  cashgoal NUMERIC,
  osar NUMERIC,
  ardays NUMERIC,
  ninetydaysar INT64,
  oneeightydaysar INT64,
  matchedgcr NUMERIC,
  matchedncr NUMERIC,
  rollingsixmonthsgcr NUMERIC,
  rollingsixmonthsncr NUMERIC,
  tablename STRING,
  fsctype STRING,
  onetwentydaysar INT64,
  threesixtydaysar INT64,
  tag STRING,
  ninetydaysaramount NUMERIC,
  onetwentydaysaramount NUMERIC,
  oneeightydaysaramount NUMERIC,
  threesixtydaysaramount NUMERIC,
  department STRING,
  financialclass STRING,
  payer STRING,
  region STRING,
  matchedosar NUMERIC,
  matchedosargt90 NUMERIC,
  matchedosargt120 NUMERIC,
  matchedardays NUMERIC,
  organizationgroupid STRING,
  batch_id STRING
)
PARTITION BY DATE(invoicecreationperiod)
CLUSTER BY department, payer, fsctype
OPTIONS (
  description='Migrated from shc_datamart.dmkpimonthend'
);
